spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=congress
    username: congress
    password: c0ngr3ss